### ISSUE TITLE
rabbitコマンドをたたいたときに表示されるメッセージについて

### ISSUE THREAD

**Issue by kojix2** [rabbit-shocker/rabbit#131]
こんにちは

```
rabbit
```

とすると、ファイル選択ダイアログとともに

```
/home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rabbit-3.0.1/lib/rabbit/command/rabbit.rb:641:in `choose_source_file_by_dialog': 'Gtk::FileChooser::ACTION_OPEN' has been deprecated. Use 'Gtk::FileChooserAction::OPEN' or ':open'.
/home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rabbit-3.0.1/lib/rabbit/command/rabbit.rb:644:in `choose_source_file_by_dialog': 'Gtk::Dialog::RESPONSE_CANCEL' has been deprecated. Use 'Gtk::ResponseType::CANCEL' or ':cancel'.
/home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rabbit-3.0.1/lib/rabbit/command/rabbit.rb:646:in `choose_source_file_by_dialog': 'Gtk::Dialog::RESPONSE_ACCEPT' has been deprecated. Use 'Gtk::ResponseType::ACCEPT' or ':accept'.
/home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rabbit-3.0.1/lib/rabbit/command/rabbit.rb:639:in `new': 'Gtk::FileChooserDialog#initialize(title, parent, action, back, *buttons)' style has been deprecated. Use 'Gtk::FileChooserDialog#initialize(:title => nil, :parent => nil, :action => :open, :buttons => nil)' style.
```
こんなメッセージが表示されます。これはコントリビューションチャンスだと思って、この警告の通りに修正してプルリクエストを送った方がいいのでしょうか。それとも、互換性のためにこのままにしておいた方がいいものなのでしょうか。

**Comment by kou** [comment]
Rabbit 3でGTK+ 2のサポートをやめたのでこの渓谷通り修正してプルリクエストを送ってください！
（定数のやつはシンボルを使ったバージョンの方が好ましいです。）

**Comment by kojix2** [comment]
送りました！
