### ISSUE TITLE
Unable to load svg image

### ISSUE THREAD

**Issue by colindean** [rabbit-shocker/rabbit#47]
https://github.com/colindean/talks/tree/master/lightning/rubocop/rubocop.md

```
[colin@kid rubocop (master)]$ rabbit rubocop.md
[WARNING]
./bark.svg: Unrecognized image file format
[WARNING]
Rabbit::ImageFileDoesNotExistError: no such file: bark.svg
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:629:in `image_element'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/background-image-toolkit/background-image-toolkit.rb:21:in `apply_background_image_property'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/body-background-image/body-background-image.rb:6:in `block (3 levels) in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/body-background-image/body-background-image.rb:5:in `each'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/body-background-image/body-background-image.rb:5:in `block (2 levels) in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:439:in `call'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:439:in `match'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/body-background-image/body-background-image.rb:1:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `instance_eval'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/searcher.rb:24:in `in_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:259:in `apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:323:in `include_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/default/default.rb:35:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `instance_eval'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/searcher.rb:24:in `in_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:259:in `apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:323:in `include_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/nari/nari.rb:58:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `instance_eval'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:260:in `block in apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/searcher.rb:24:in `in_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/applier.rb:259:in `apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/theme/manager.rb:22:in `apply'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:657:in `_apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:305:in `apply_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:321:in `reload_theme'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:335:in `block in parse'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:726:in `keep_index'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/canvas.rb:330:in `parse'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/frame.rb:56:in `parse'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/command/rabbit.rb:702:in `parse'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/command/rabbit.rb:864:in `do_display'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/command/rabbit.rb:51:in `run'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/lib/rabbit/command/rabbit.rb:29:in `run'
/Users/colin/.rvm/gems/ruby-2.1.3/gems/rabbit-2.1.3/bin/rabbit:22:in `<top (required)>'
/Users/colin/.rvm/gems/ruby-2.1.3/bin/rabbit:23:in `load'
/Users/colin/.rvm/gems/ruby-2.1.3/bin/rabbit:23:in `<main>'
/Users/colin/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/colin/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

`gem list`

```
atk (2.2.2, 2.1.0)
bigdecimal (1.2.4)
bundler (1.7.3)
bundler-unload (1.0.2)
cairo (1.12.9, 1.12.8)
coderay (1.1.0)
eventmachine (1.0.3)
executable-hooks (1.3.2)
faraday (0.9.0)
gdk_pixbuf2 (2.2.2, 2.1.0)
gem-wrappers (1.2.4)
gettext (3.1.4, 3.1.1)
gio2 (2.1.0)
glib2 (2.2.2, 2.1.0)
gtk2 (2.1.0)
hikidoc (0.0.6)
http_parser.rb (0.5.3)
io-console (0.4.2)
json (1.8.1)
kramdown (1.3.2)
locale (2.1.0)
mime-types (2.1)
mini_portile (0.5.2)
minitest (4.7.5)
multipart-post (2.0.0)
nokogiri (1.6.1)
oauth (0.4.7)
pango (2.1.0)
pkg-config (1.1.5)
poppler (2.1.0)
psych (2.0.5)
rabbit (2.1.3, 2.1.2)
rabbiter (2.0.1)
rake (10.1.0)
rdoc (4.1.0)
rdtool (0.6.38)
rsvg2 (2.1.0)
rttool (1.0.3.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
simple_oauth (0.1.9)
test-unit (2.1.3.0)
text (1.3.0, 1.2.3)
twitter-stream (0.1.16)
twitter_oauth (0.4.94)
```

**Comment by kou** [comment]
I hope that this has been solved the latest version.
