### ISSUE TITLE
2.1.4 test_codeblock_fence fails on Fedora 21 

### ISSUE THREAD

**Issue by mtasaka** [rabbit-shocker/rabbit#54]
At least on Fedora 21 2.1.4 test_codeblock_fence fails like
```
Error: test_codeblock_fence(RabbitParserMarkdownTest::BodyTest::BlockDiagTest)
: NoMethodError: private method `warn' called for nil:NilClass
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/ext/image.rb:32:in `rescue in make_image_from_file'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/ext/image.rb:29:in `make_image_from_file'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:290:in `convert_codeblock_language'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:266:in `convert_codeblock'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:34:in `block in convert_container'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:33:in `each'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:33:in `convert_container'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:48:in `convert_root'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/lib/rabbit/parser/markdown.rb:70:in `parse'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/test/parser/test-markdown.rb:33:in `parse'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/test/parser/test-markdown.rb:82:in `parse'
/home/mtasaka/rpmbuild/TEMP/rubygem-rabbit/git/rabbit/test/parser/test-markdown.rb:259:in `test_codeblock_fence'
     256:                          ""
     257:                        ],
     258:                      ],
  => 259:                      parse(<<-MARKDOWN))
     260: ```blockdiag
     261: {
     262:   A -> B -> C;
```

**Comment by kou** [comment]
Thanks for your report!
I've fixed it. But it may cause another failure...

**Comment by mtasaka** [comment]
Okay, now it clearly shows that "blockdiag" executable is needed for test (available in python-blockdiag rpm on Fedora), and with it test succeeds, thank you!
