### ISSUE TITLE
Undefined method _ for Converter in convert_p for Markdown

### ISSUE THREAD

**Issue by colindean** [rabbit-shocker/rabbit#71]
Markdown file producing error here:

https://github.com/colindean/talks/blob/d617f8ed252cd90b1b8f8ba66cef8660f2534d41/lightning/mosh/mosh.md

Initially encountered with rabbit 2.1.6 on Ruby 2.1.3:

```
/Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:150:in `convert_p': undefined method `_' for #<Rabbit::Parser::Markdown::Converter:0x007f90aa59ff28> (NoMethodError)
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:34:in `block in convert_container'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:33:in `each'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:33:in `convert_container'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:48:in `convert_root'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser/markdown.rb:70:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/parser.rb:19:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:333:in `block in parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:726:in `keep_index'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:330:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/frame.rb:56:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:703:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:865:in `do_display'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:51:in `run'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:29:in `run'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/gems/rabbit-2.1.6/bin/rabbit:22:in `<top (required)>'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/bin/rabbit:23:in `load'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/bin/rabbit:23:in `<main>'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/bin/ruby_executable_hooks:15:in `eval'
        from /Users/colin/.rvm/gems/ruby-2.1.3@talks/bin/ruby_executable_hooks:15:in `<main>'
```

Bumped up to Ruby 2.2.2:

```
/Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/ext/entity.rb:355: warning: duplicated key at line 2409 ignored: "Dagger"
/Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/ext/entity.rb:357: warning: duplicated key at line 2411 ignored: "dagger"
/Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:150:in `convert_p': undefined method `_' for #<Rabbit::Parser::Markdown::Converter:0x007fe18fb51af8> (NoMethodError)
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:34:in `block in convert_container'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:33:in `each'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:33:in `convert_container'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:48:in `convert_root'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown/converter.rb:27:in `convert'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser/markdown.rb:70:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/parser.rb:19:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:333:in `block in parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:726:in `keep_index'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/canvas.rb:330:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/frame.rb:56:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:703:in `parse'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:865:in `do_display'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:51:in `run'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/lib/rabbit/command/rabbit.rb:29:in `run'
        from /Users/colin/.rvm/gems/ruby-2.2.2/gems/rabbit-2.1.6/bin/rabbit:22:in `<top (required)>'
        from /Users/colin/.rvm/gems/ruby-2.2.2/bin/rabbit:23:in `load'
        from /Users/colin/.rvm/gems/ruby-2.2.2/bin/rabbit:23:in `<main>'
        from /Users/colin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/colin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by colindean** [comment]
Ah, looks like gettext isn't in scope there?

**Comment by colindean** [comment]
But at least now I see what I'm doing wrong and was able to fix it. Rabbit does not like anything on a line with an image, apparently: just the image.

**Comment by kou** [comment]
> Ah, looks like gettext isn't in scope there?

Right. I've fixed it.

Thanks for your report!

**Comment by colindean** [comment]
:-)
